default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['BOOKSTORE_DATABASE_USERNAME'] %>
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: BookStore_development

test:
  <<: *default
  database: BookStore_test

production:
  <<: *default
  database: BookStore_production
