Author.create!([
  {first_name: "Erika Leonard", last_name: "James", description: "Born in London in 1963, British writer Erika Leonard is better known by her pen name, E. L. James. James studied history at the University of Kent and worked as a television executive. Her erotic romance trilogy, of which Fifty Shades of Grey was the first published, has sold over 35 million copies in the U.S. and over 70 million worldwide. They set a record as the fastest selling paperback of all time. James was named one of \"The World's Most Influential People in 2012.\" The film adaptation of Fifty Shades of Grey will be released in 2015. James currently lives in London."},
  {first_name: "Laurell", last_name: "K. Hamilton", description: "Laurell K. Hamilton (b. Laurell Kaye Klein on February 19th, 1963 in Heber Springs, Arkansas) is a New York Times-bestselling American author, best known for writing two popular fantasy/romance series. The Anita Blake: Vampire Hunter follows the title character, a vampire executioner with supernatural powers, and contains over 20 books. The eight book Merry Gentry series follows the title character, a faerie princess and private investigator. Hamilton also wrote a comic book series based on the Anita Blake novels."},
  {first_name: "Francine", last_name: "Rivers", description: "From 1976 to 1985, Francine Rivers had a successful writing career in the general market, and her books were awarded or nominated for numerous awards and prizes. Although raised in a religious home, Francine did not truly encounter Christ until later in life, when she was already a wife, mother of three, and an established romance novelist. Shortly after becoming a born-again Christian in 1986, Francine wrote Redeeming Love as her statement of faith."},
  {first_name: "Homer", last_name: " ", description: "Ancient Greek poet Homer established the gold standard for heroic quests and sweeping journeys with his pair of classic epic poems, The Iliad and The Odyssey."},
  {first_name: "William", last_name: "Davis", description: "William R. Davis is a Milwaukee-based American cardiologist and author of health books known for his stance against \"modern wheat\", which he labels a \"perfect, chronic poison.\" This view had previously been rejected by the medical and agricultural industry based on conjecture, minimal controlled studies, and challenges inherent to clinical research, however anecdotal evidence such as Dr. Davis's and among many patients in the western populace suggest more research is necessary to understand and measure physiological and psychological influences that gluten and today's contemporary cultivars of wheat may have on human health apart from non-therapeutic dietary trends. In a recent double-blind placebo controlled challenge, approximately 14% of patients experienced symptomatic relapse upon gluten challenge, suggesting those individuals to have a bona fide non-celiac gluten sensitivity (NCGS)."},
  {first_name: "Michael", last_name: "Pollan", description: "Michael Pollan is a professor of journalism at the University of California at Berkeley, a contributing writer for The New York Times, and a bestselling author of witty, offbeat nonfiction that examines various aspects of the agricultural industry, the food chain, and man's place in the natural world."},
  {first_name: "Bill", last_name: "Bryson", description: "Bill Bryson (born on December 8th, 1951 in Des Moines, Iowa) is a bestselling American non-fiction author of several travel and academic books. His travel books tend to be humorous in tone; his first, Notes from a Small Island, about his the 20 years he spent in Britain. His non-travel writing focuses on the English language and science. He was awarded an honorary OBE (Order of the British Empire) for his accomplishments in literature."},
  {first_name: "Elaine", last_name: "Nicpon Marieb", description: ""},
  {first_name: "Jon", last_name: "B. Mallatt", description: ""},
  {first_name: "Matt", last_name: "Hutchinson", description: ""},
  {first_name: "Gary", last_name: "Paulsen", description: "Gary Paulsen is one of the most honored writers of contemporary literature for young readers. He has written more than one hundred book for adults and young readers, and is the author of three Newbery Honor titles: Dogsong, Hatchet, and The Winter Room. He divides his time among Alaska, New Mexico, Minnesota, and the Pacific."}
])
Book.create!([
  {title: "Fifty Shades of Grey: Book One of the Fifty Shades Trilogy (Fifty Shades of Grey Series)", short_description: "MORE THAN 100 MILLION COPIES SOLD WORDWIDENOW A MAJOR MOTION PICTUREWhen literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating.", full_description: "MORE THAN 100 MILLION COPIES SOLD WORDWIDENOW A MAJOR MOTION PICTUREWhen literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating. The unworldly, innocent Ana is startled to realize she wants this man and, despite his enigmatic reserve, finds she is desperate to get close to him. Unable to resist Ana’s quiet beauty, wit, and independent spirit, Grey admits he wants her, too—but on his own terms. Shocked yet thrilled by Grey’s singular erotic tastes, Ana hesitates. For all the trappings of success—his multinational businesses, his vast wealth, his loving family—Grey is a man tormented by demons and consumed by the need to control. When the couple embarks on a daring, passionately physical affair, Ana discovers Christian Grey’s secrets and explores her own dark desires.This book is intended for mature audiences.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/1/51RhsdrKNHL._SL300_.jpg")),
    price: "3.59"},
  {title: "Fifty Shades Freed: Book Three of the Fifty Shades Trilogy (Fifty Shades of Grey Series)", short_description: "MORE THAN 100 MILLION COPIES SOLD WORLDWIDEFIFTY SHADES OF GREY IS NOW A MAJOR MOTION PICTUREWhen unworldly student Anastasia Steele first encountered the driven and dazzling young entrepreneur Christian Grey it sparked a sensual affair that changed both of their lives irrevocably.", full_description: "MORE THAN 100 MILLION COPIES SOLD WORLDWIDEFIFTY SHADES OF GREY IS NOW A MAJOR MOTION PICTUREWhen unworldly student Anastasia Steele first encountered the driven and dazzling young entrepreneur Christian Grey it sparked a sensual affair that changed both of their lives irrevocably. Shocked, intrigued, and, ultimately, repelled by Christian’s singular erotic tastes, Ana demands a deeper commitment. Determined to keep her, Christian agrees. Now, Ana and Christian have it all—love, passion, intimacy, wealth, and a world of possibilities for their future. But Ana knows that loving her Fifty Shades will not be easy, and that being together will pose challenges that neither of them would anticipate. Ana must somehow learn to share Christian’s opulent lifestyle without sacrificing her own identity. And Christian must overcome his compulsion to control as he wrestles with the demons of a tormented past. Just when it seems that their strength together will eclipse any obstacle, misfortune, malice, and fate conspire to make Ana’s deepest fears turn to reality.This book is intended for mature audiences.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/2/51TChFM9hXL._SL300_.jpg")),
    price: "3.59"},
  {title: "Guilty Pleasures: An Anita Blake, Vampire Hunter Novel", short_description: "Anita Blake may be small and young, but vampires call her the Executioner. Anita is a necromancer and vampire hunter in a time when vampires are protected by law--as long as they don't get too nasty.", full_description: "Anita Blake may be small and young, but vampires call her the Executioner. Anita is a necromancer and vampire hunter in a time when vampires are protected by law--as long as they don't get too nasty. Now someone's killing innocent vampires and Anita agrees--with a bit of vampiric arm-twisting--to help figure out who and why. Trust is a luxury Anita can't afford when her allies aren't human. The city's most powerful vampire, Nikolaos, is 1,000 years old and looks like a 10-year-old girl. The second most powerful vampire, Jean-Claude, is interested in more than just Anita's professional talents, but the feisty necromancer isn't playing along--yet. This popular series has a wild energy and humor, and some very appealing characters--both dead and alive.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/3/41N4y2vmRqL._SL300_.jpg")),
    price: "4.29"},
  {title: "An Echo in the Darkness (Mark of the Lion #2)", short_description: "This classic series has inspired nearly 2 million readers. Both loyal fans and new readers will want the latest edition of this beloved series. This edition includes a foreword from the publisher, a preface from Francine Rivers and discussion questions suitable for personal and group use.", full_description: "This classic series has inspired nearly 2 million readers. Both loyal fans and new readers will want the latest edition of this beloved series. This edition includes a foreword from the publisher, a preface from Francine Rivers and discussion questions suitable for personal and group use. #2 An Echo in the Darkness: Turning away from the opulence of Rome, Marcus is led by a whispering voice from the past into a journey that could set him free from the darkness of his soul.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/4/51ibnriZeEL._SL300_.jpg")),
    price: "4.29"},
  {title: "The Iliad", short_description: "Humans and gods wrestling with towering emotions. Men fighting to the death amidst the devastation and destruction of the Trojan War. To this day, the heroism and adventure in The Iliad have remained unmatched in song and story.", full_description: "Humans and gods wrestling with towering emotions. Men fighting to the death amidst the devastation and destruction of the Trojan War. To this day, the heroism and adventure in The Iliad have remained unmatched in song and story.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/5/51RfFkD0UeL._SL300_.jpg")),
    price: "5.89"},
  {title: "Wheat Belly: Lose the Wheat, Lose the Weight, and Find Your Path Back to Health ", short_description: "A renowned cardiologist explains how eliminating wheat from our diets can prevent fat storage,shrink unsightly bulges, and reverse myriad health problems. Every day, over 200 million Americans consume food products made of wheat.", full_description: "A renowned cardiologist explains how eliminating wheat from our diets can prevent fat storage,shrink unsightly bulges, and reverse myriad health problems. Every day, over 200 million Americans consume food products made of wheat. As a result, over 100million of them experience some form of adverse health effect, ranging from minor rashes and high blood sugar to the unattractive stomach bulges that preventive cardiologist William Davis calls \"wheat bellies.\" According to Davis, that excess fat has nothing to do with gluttony, sloth, or too much butter: It’s due to the whole grain wraps we eat for lunch. After witnessing over 2,000 patients regain their health after giving up wheat, Davis reached thedisturbing conclusion that wheat is the single largest contributor to the nationwide obesity epidemic—and its elimination is key to dramatic weight loss and optimal health. In Wheat Belly, Davis exposes the harmful effects of what is actually a product of genetic tinkering and agribusiness being sold to theAmerican public as \"wheat\"—and provides readers with a user-friendly, step-by-step plan to navigate a new, wheat-free lifestyle.Informed by cutting-edge science and nutrition, along with case studies from men and women whohave experienced life-changing transformations in their health after waving goodbye to wheat, WheatBelly is an illuminating look at what is truly making Americans sick and an action plan to clear our plates of this seemingly benign ingredient.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/6/51Z83dLKJPL._SL300_.jpg")),
    price: "3.49"},
  {title: "In Defense of Food: An Eater's Manifesto", short_description: "Amazon Significant Seven, January 2008: Food is the one thing that Americans hate to love and, as it turns out, love to hate. What we want to eat has been ousted by the notion of what we should eat, and it's at this nexus of hunger and hang-up that Michael Pollan poses his most salient question: where is the food in our food?", full_description: "Amazon Significant Seven, January 2008: Food is the one thing that Americans hate to love and, as it turns out, love to hate. What we want to eat has been ousted by the notion of what we should eat, and it's at this nexus of hunger and hang-up that Michael Pollan poses his most salient question: where is the food in our food? What follows in In Defense of Food is a series of wonderfully clear and thoughtful answers that help us omnivores navigate the nutritional minefield that's come to typify our food culture. Many processed foods vie for a spot in our grocery baskets, claiming to lower cholesterol, weight, glucose levels, you name it. Yet Pollan shows that these convenient \"healthy\" alternatives to whole foods are appallingly inconvenient: our health has a nation has only deteriorated since we started exiling carbs, fats--even fruits--from our daily meals. His razor-sharp analysis of the American diet (as well as its architects and its detractors) offers an inspiring glimpse of what it would be like if we could (a la Humpty Dumpty) put our food back together again and reconsider what it means to eat well. In a season filled with rallying cries to lose weight and be healthy, Pollan's call to action—\"Eat food. Not too much. Mostly plants.\"--is a program I actually want to follow. --Anne Bartholomew",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/7/41vwZGvZLLL._SL300_.jpg")),
    price: "4.19"},
  {title: "A Short History of Nearly Everything", short_description: "From primordial nothingness to this very moment, A Short History of Nearly Everything reports what happened and how humans figured it out. To accomplish this daunting literary task, Bill Bryson uses hundreds of sources, from popular science books to interviews with luminaries in various fields.", full_description: "From primordial nothingness to this very moment, A Short History of Nearly Everything reports what happened and how humans figured it out. To accomplish this daunting literary task, Bill Bryson uses hundreds of sources, from popular science books to interviews with luminaries in various fields. His aim is to help people like him, who rejected stale school textbooks and dry explanations, to appreciate how we have used science to understand the smallest particles and the unimaginably vast expanses of space. With his distinctive prose style and wit, Bryson succeeds admirably. Though A Short History clocks in at a daunting 500-plus pages and covers the same material as every science book before it, it reads something like a particularly detailed novel (albeit without a plot). Each longish chapter is devoted to a topic like the age of our planet or how cells work, and these chapters are grouped into larger sections such as \"The Size of the Earth\" and \"Life Itself.\" Bryson chats with experts like Richard Fortey (author of Life and Trilobite) and these interviews are charming. But it's when Bryson dives into some of science's best and most embarrassing fights--Cope vs. Marsh, Conway Morris vs. Gould--that he finds literary gold. --Therese Littleton",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/8/41Z3XNXTcHL._SL300_.jpg")),
    price: "4.6"},
  {title: "Human Anatomy & Physiology (5th Edition)", short_description: "Elaine Marieb's engaging writing style and meticulous attention to the learning needs of students continue to be hallmarks of this market-leading text. The author not only reports the latest research and advancements in the field, she does so with a sense of fascination and encouragement.", full_description: "Elaine Marieb's engaging writing style and meticulous attention to the learning needs of students continue to be hallmarks of this market-leading text. The author not only reports the latest research and advancements in the field, she does so with a sense of fascination and encouragement. Every chapter has been scrutinized with the goal of helping students understand core concepts and apply their knowledge to new situations. In addition, the text and supplements package offers a convenient, integrated learning system. For example, new end-of-chapter \"Learning with Technology\" sections make using CD-ROM and Internet resources easier than ever.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/9/41S41R5GY3L._SL300_.jpg")),
    price: "7.85"},
  {title: "A Brief Atlas of the Human Body", short_description: "This full-color atlas includes 107 bone and 47 soft-tissue photographs with easy-to-read labels. This new edition of the atlas contains a brand new comprehensive histology photomicrograph section featuring over 50 slides of basic tissue and organ systems.", full_description: "This full-color atlas includes 107 bone and 47 soft-tissue photographs with easy-to-read labels. This new edition of the atlas contains a brand new comprehensive histology photomicrograph section featuring over 50 slides of basic tissue and organ systems. Featuring photos taken by renowned biomedical photographer Ralph Hutchings, this high-quality photographic atlas makes an excellent resource for the classroom and laboratory, and is referenced in appropriate figure legends throughout the text.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/10/4157ZE720ML._SL300_.jpg")),
    price: "4.39"},
  {title: "Hatchet", short_description: "Thirteen-year-old Brian Robeson is on his way to visit his father when the single-engine plane in which he is flying crashes. Suddenly, Brian finds himself alone in the Canadian wilderness with nothing but a tattered Windbreaker and the hatchet his mother gave him as a present -- and the dreadful secret that has been tearing him apart since his parent's divorce.", full_description: "Thirteen-year-old Brian Robeson is on his way to visit his father when the single-engine plane in which he is flying crashes. Suddenly, Brian finds himself alone in the Canadian wilderness with nothing but a tattered Windbreaker and the hatchet his mother gave him as a present -- and the dreadful secret that has been tearing him apart since his parent's divorce. But now Brian has no time for anger, self pity, or despair -- it will take all his know-how and determination, and more courage than he knew he possessed, to survive. For twenty years Gary Paulsen's award-winning contemporary classic has been the survival story with which all others are compared. This new edition, with a reading group guide, will introduce a new generation of readers to this page-turning, heart-stopping adventure.",
    image: File.open(File.join(Rails.root, "public/seeds/uploads/book/image/11/41lO2e0xt3L._SL300_.jpg")),
    price: "3.59"}
])
Category.create!([
  {name: "Cooking"},
  {name: "Children's Books"},
  {name: "Science & Math"},
  {name: "Romance"},
  {name: "History"}
])
Book::HABTM_Authors.create!([
  {author_id: 1, book_id: 1},
  {author_id: 1, book_id: 2},
  {author_id: 2, book_id: 3},
  {author_id: 3, book_id: 4},
  {author_id: 4, book_id: 5},
  {author_id: 5, book_id: 6},
  {author_id: 6, book_id: 7},
  {author_id: 7, book_id: 8},
  {author_id: 8, book_id: 9},
  {author_id: 9, book_id: 9},
  {author_id: 9, book_id: 10},
  {author_id: 10, book_id: 10},
  {author_id: 11, book_id: 11}
])
Book::HABTM_Categories.create!([
  {book_id: 1, category_id: 5},
  {book_id: 2, category_id: 5},
  {book_id: 3, category_id: 5},
  {book_id: 4, category_id: 5},
  {book_id: 4, category_id: 2},
  {book_id: 5, category_id: 3},
  {book_id: 5, category_id: 2},
  {book_id: 6, category_id: 1},
  {book_id: 7, category_id: 1},
  {book_id: 8, category_id: 4},
  {book_id: 8, category_id: 2},
  {book_id: 9, category_id: 4},
  {book_id: 10, category_id: 4},
  {book_id: 11, category_id: 3}
])
Coupon.create!([
  {code: "0003", discount: "0.15", used: false, order_id: nil},
  {code: "0004", discount: "0.2", used: false, order_id: nil},
  {code: "0002", discount: "0.1", used: false, order_id: nil},
  {code: "0001", discount: "0.05", used: false, order_id: nil}
])
Delivery.create!([
  {delivery_type: "UPS Ground", price: "5.0"},
  {delivery_type: "UPS Two Day", price: "10.0"},
  {delivery_type: "UPS One Day", price: "15.0"}
])
OrderState.create!([
  {state: "in progress", id_of_state: 1},
  {state: "in queue", id_of_state: 2},
  {state: "in delivery", id_of_state: 3},
  {state: "delivered", id_of_state: 4},
  {state: "canceled", id_of_state: 5}
])
User.create!([
  {email: ENV['ADMIN_EMAIL'], password: ENV['ADMIN_PASSWORD'], password_confirmation: ENV['ADMIN_PASSWORD'], reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 99, current_sign_in_at: "2016-09-07 11:53:50", last_sign_in_at: "2016-09-06 17:00:11", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", failed_attempts: 0, unlock_token: nil, locked_at: nil},
  {email: ENV['USER_EMAIL'], password: ENV['USER_PASSWORD'], password_confirmation: ENV['USER_PASSWORD'], reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2016-07-24 11:23:03", last_sign_in_at: "2016-07-16 09:00:24", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", failed_attempts: 0, unlock_token: nil, locked_at: nil},
])
